export const flightSchedules = [
    
        {
        airline: "Garuda Indonesia",
        flightNumber: "GA407",
        origin: "SUB",
        originCity: "Surabaya",
        originAirport: "Juanda International Airport",
        destination: "DPS",
        destinationCity: "Bali",
        destinationAirport: "Ngurah Rai International Airport",
        date: "20/02/2025",
        departure: "08:00",
        arrival: "09:30",
        aircraft: "Boeing 737-800",
        price: 1500000,
        seatsAvailable: 120,
        class: "Economy",
        baggage: "20kg",
        meal: true
        },
        {
        airline: "Lion Air",
        flightNumber: "JT642",
        origin: "SUB",
        originCity: "Surabaya",
        originAirport: "Juanda International Airport",
        destination: "DPS",
        destinationCity: "Bali",
        destinationAirport: "Ngurah Rai International Airport",
        date: "20/02/2025",
        departure: "11:45",
        arrival: "13:15",
        aircraft: "Airbus A320",
        price: 980000,
        seatsAvailable: 85,
        class: "Economy",
        baggage: "15kg",
        meal: false
        },
    
        
        {
        airline: "Citilink",
        flightNumber: "QG889",
        origin: "CGK",
        originCity: "Jakarta",
        originAirport: "Soekarno-Hatta International Airport",
        destination: "DPS",
        destinationCity: "Bali",
        destinationAirport: "Ngurah Rai International Airport",
        date: "21/02/2025",
        departure: "06:30",
        arrival: "09:00",
        aircraft: "ATR 72-600",
        price: 1200000,
        seatsAvailable: 60,
        class: "Economy",
        baggage: "20kg",
        meal: true
        },
        {
        airline: "Batik Air",
        flightNumber: "ID6583",
        origin: "CGK",
        originCity: "Jakarta",
        originAirport: "Soekarno-Hatta International Airport",
        destination: "DPS",
        destinationCity: "Bali",
        destinationAirport: "Ngurah Rai International Airport",
        date: "21/02/2025",
        departure: "14:20",
        arrival: "16:50",
        aircraft: "Boeing 737 MAX 8",
        price: 2100000,
        seatsAvailable: 30,
        class: "Business",
        baggage: "30kg",
        meal: true
        },
    
        
        {
        airline: "AirAsia",
        flightNumber: "QZ755",
        origin: "CGK",
        originCity: "Jakarta",
        originAirport: "Soekarno-Hatta International Airport",
        destination: "SUB",
        destinationCity: "Surabaya",
        destinationAirport: "Juanda International Airport",
        date: "22/02/2025",
        departure: "18:15",
        arrival: "19:30",
        aircraft: "Airbus A320",
        price: 750000,
        seatsAvailable: 95,
        class: "Economy",
        baggage: "15kg",
        meal: false
        },
    
        
        {
        airline: "Super Air Jet",
        flightNumber: "IU665",
        origin: "DPS",
        originCity: "Denpasar",
        originAirport: "Ngurah Rai International Airport",
        destination: "JOG",
        destinationCity: "Yogyakarta",
        destinationAirport: "Adisutjipto International Airport",
        date: "23/02/2025",
        departure: "10:00",
        arrival: "11:15",
        aircraft: "Airbus A320neo",
        price: 890000,
        seatsAvailable: 110,
        class: "Economy",
        baggage: "20kg",
        meal: true
        },
    
        
        {
        airline: "Garuda Indonesia",
        flightNumber: "GA182",
        origin: "CGK",
        originCity: "Jakarta",
        originAirport: "Soekarno-Hatta International Airport",
        destination: "KNO",
        destinationCity: "Medan",
        destinationAirport: "Kualanamu International Airport",
        date: "24/02/2025",
        departure: "07:00",
        arrival: "09:30",
        aircraft: "Boeing 737-800",
        price: 2000000,
        seatsAvailable: 80,
        class: "Economy",
        baggage: "20kg",
        meal: true
        },
    
        {
        airline: "Lion Air",
        flightNumber: "JT782",
        origin: "SUB",
        originCity: "Surabaya",
        originAirport: "Juanda International Airport",
        destination: "UPG",
        destinationCity: "Makassar",
        destinationAirport: "Sultan Hasanuddin International Airport",
        date: "25/02/2025",
        departure: "13:00",
        arrival: "15:30",
        aircraft: "Boeing 737-900ER",
        price: 1350000,
        seatsAvailable: 70,
        class: "Economy",
        baggage: "15kg",
        meal: false
        },
    
        {
        airline: "Citilink",
        flightNumber: "QG902",
        origin: "JOG",
        originCity: "Yogyakarta",
        originAirport: "Adisutjipto International Airport",
        destination: "BPN",
        destinationCity: "Balikpapan",
        destinationAirport: "Sultan Aji Muhammad Sulaiman International Airport",
        date: "26/02/2025",
        departure: "16:45",
        arrival: "18:30",
        aircraft: "ATR 72-600",
        price: 1100000,
        seatsAvailable: 55,
        class: "Economy",
        baggage: "20kg",
        meal: true
        },
        {
            airline: "Sriwijaya Air",
            flightNumber: "SJ234",
            origin: "CGK",
            originCity: "Jakarta",
            originAirport: "Soekarno-Hatta International Airport",
            destination: "PDG",
            destinationCity: "Padang",
            destinationAirport: "Minangkabau International Airport",
            date: "27/02/2025",
            departure: "09:00",
            arrival: "10:30",
            aircraft: "Boeing 737-500",
            price: 850000,
            seatsAvailable: 65,
            class: "Economy",
            baggage: "20kg",
            meal: true
          },
          {
            airline: "Lion Air",
            flightNumber: "JT881",
            origin: "DPS",
            originCity: "Bali",
            originAirport: "Ngurah Rai International Airport",
            destination: "LOP",
            destinationCity: "Lombok",
            destinationAirport: "Lombok International Airport",
            date: "28/02/2025",
            departure: "12:15",
            arrival: "12:45",
            aircraft: "ATR 72-600",
            price: 450000,
            seatsAvailable: 40,
            class: "Economy",
            baggage: "15kg",
            meal: false
          },
          {
            airline: "Batik Air",
            flightNumber: "ID774",
            origin: "SUB",
            originCity: "Surabaya",
            originAirport: "Juanda International Airport",
            destination: "BPN",
            destinationCity: "Balikpapan",
            destinationAirport: "Sultan Aji Muhammad Sulaiman Airport",
            date: "01/03/2025",
            departure: "14:00",
            arrival: "16:15",
            aircraft: "Airbus A320neo",
            price: 1250000,
            seatsAvailable: 90,
            class: "Business",
            baggage: "30kg",
            meal: true
          },
          {
            airline: "Citilink",
            flightNumber: "QG455",
            origin: "UPG",
            originCity: "Makassar",
            originAirport: "Sultan Hasanuddin International Airport",
            destination: "AMQ",
            destinationCity: "Ambon",
            destinationAirport: "Pattimura Airport",
            date: "02/03/2025",
            departure: "07:30",
            arrival: "09:45",
            aircraft: "ATR 72-600",
            price: 950000,
            seatsAvailable: 50,
            class: "Economy",
            baggage: "20kg",
            meal: true
          },
          {
            airline: "Garuda Indonesia",
            flightNumber: "GA889",
            origin: "JOG",
            originCity: "Yogyakarta",
            originAirport: "Adisutjipto International Airport",
            destination: "BTH",
            destinationCity: "Batam",
            destinationAirport: "Hang Nadim Airport",
            date: "03/03/2025",
            departure: "10:45",
            arrival: "12:30",
            aircraft: "Boeing 737-800",
            price: 1650000,
            seatsAvailable: 75,
            class: "Economy",
            baggage: "20kg",
            meal: true
          },
          {
            airline: "AirAsia",
            flightNumber: "QZ332",
            origin: "KNO",
            originCity: "Medan",
            originAirport: "Kualanamu International Airport",
            destination: "PNK",
            destinationCity: "Pontianak",
            destinationAirport: "Supadio International Airport",
            date: "04/03/2025",
            departure: "16:20",
            arrival: "18:00",
            aircraft: "Airbus A320",
            price: 680000,
            seatsAvailable: 85,
            class: "Economy",
            baggage: "15kg",
            meal: false
          },
          {
            airline: "Super Air Jet",
            flightNumber: "IU997",
            origin: "DPS",
            originCity: "Bali",
            originAirport: "Ngurah Rai International Airport",
            destination: "SOC",
            destinationCity: "Solo",
            destinationAirport: "Adisumarmo International Airport",
            date: "05/03/2025",
            departure: "08:45",
            arrival: "10:15",
            aircraft: "Airbus A320",
            price: 920000,
            seatsAvailable: 60,
            class: "Economy",
            baggage: "20kg",
            meal: true
          },
          {
            airline: "Nam Air",
            flightNumber: "IN556",
            origin: "PKU",
            originCity: "Pekanbaru",
            originAirport: "Sultan Syarif Kasim II Airport",
            destination: "PLM",
            destinationCity: "Palembang",
            destinationAirport: "Sultan Mahmud Badaruddin II Airport",
            date: "06/03/2025",
            departure: "13:10",
            arrival: "14:20",
            aircraft: "Boeing 737-300",
            price: 550000,
            seatsAvailable: 45,
            class: "Economy",
            baggage: "15kg",
            meal: false
          },
          {
            airline: "Wings Air",
            flightNumber: "IW223",
            origin: "BTJ",
            originCity: "Banda Aceh",
            originAirport: "Sultan Iskandar Muda Airport",
            destination: "MEQ",
            destinationCity: "Meulaboh",
            destinationAirport: "Cut Nyak Dhien Airport",
            date: "07/03/2025",
            departure: "11:30",
            arrival: "11:50",
            aircraft: "ATR 72-500",
            price: 350000,
            seatsAvailable: 30,
            class: "Economy",
            baggage: "15kg",
            meal: false
          },
          {
            airline: "Batik Air",
            flightNumber: "ID432",
            origin: "BDO",
            originCity: "Bandung",
            originAirport: "Husein Sastranegara International Airport",
            destination: "SRG",
            destinationCity: "Semarang",
            destinationAirport: "Achmad Yani International Airport",
            date: "08/03/2025",
            departure: "17:00",
            arrival: "17:45",
            aircraft: "Embraer E190",
            price: 620000,
            seatsAvailable: 55,
            class: "Business",
            baggage: "25kg",
            meal: true
          }
  
  ];
  